name: 01_lint

on:
  push:
    branches:
      - "*"
jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: v16.3.0
      - name: Install dependencies
        run: |
          npm install
      - name: lint
        run: |
          npm run fmt
          npm run lint
